### ISSUE TITLE
[JOSS] Contributing Guidelines

### ISSUE THREAD

**Issue by amritagos** [giorginolab/plumed2-pycv#2]
Part of https://github.com/openjournals/joss-reviews/issues/1773. The contributing guidelines should be in their own heading at least, and possibly in a file at the root of the repository, labelled `CONTRIBUTING`, with more details.

**Comment by tonigi** [comment]
Introduced the heading in b0855a40e1c96c8c6e0174e5f61489bd81f78e68 .

**Comment by amritagos** [comment]
That will be sufficient, thanks.
